INSERT INTO countries (id, name) VALUES (1, 'Albania');
INSERT INTO countries (id, name) VALUES (2, 'Andorra');
INSERT INTO countries (id, name) VALUES (3, 'Austria');
INSERT INTO countries (id, name) VALUES (4, 'Belarus');
INSERT INTO countries (id, name) VALUES (5, 'Belgium');
INSERT INTO countries (id, name) VALUES (6, 'Bosnia and Herzegovina');
INSERT INTO countries (id, name) VALUES (7, 'Bulgaria');
INSERT INTO countries (id, name) VALUES (8, 'Croatia');
INSERT INTO countries (id, name) VALUES (9, 'Cyprus');
INSERT INTO countries (id, name) VALUES (10, 'Czech Republic');
INSERT INTO countries (id, name) VALUES (11, 'Denmark');
INSERT INTO countries (id, name) VALUES (12, 'Estonia');
INSERT INTO countries (id, name) VALUES (13, 'Finland');
INSERT INTO countries (id, name) VALUES (14, 'France');
INSERT INTO countries (id, name) VALUES (15, 'Germany');
INSERT INTO countries (id, name) VALUES (16, 'Greece');
INSERT INTO countries (id, name) VALUES (17, 'Hungary');
INSERT INTO countries (id, name) VALUES (18, 'Iceland');
INSERT INTO countries (id, name) VALUES (19, 'Ireland');
INSERT INTO countries (id, name) VALUES (20, 'Italy');
INSERT INTO countries (id, name) VALUES (21, 'Latvia');
INSERT INTO countries (id, name) VALUES (22, 'Liechtenstein');
INSERT INTO countries (id, name) VALUES (23, 'Lithuania');
INSERT INTO countries (id, name) VALUES (24, 'Luxembourg');
INSERT INTO countries (id, name) VALUES (25, 'Malta');
INSERT INTO countries (id, name) VALUES (26, 'Moldova');
INSERT INTO countries (id, name) VALUES (27, 'Monaco');
INSERT INTO countries (id, name) VALUES (28, 'Montenegro');
INSERT INTO countries (id, name) VALUES (29, 'Netherlands');
INSERT INTO countries (id, name) VALUES (30, 'The former Yougoslav Republic Of Macedonia');
INSERT INTO countries (id, name) VALUES (31, 'Norway');
INSERT INTO countries (id, name) VALUES (32, 'Poland');
INSERT INTO countries (id, name) VALUES (33, 'Portugal');
INSERT INTO countries (id, name) VALUES (34, 'Romania');
INSERT INTO countries (id, name) VALUES (35, 'Russia');
INSERT INTO countries (id, name) VALUES (36, 'San Marino');
INSERT INTO countries (id, name) VALUES (37, 'Serbia');
INSERT INTO countries (id, name) VALUES (38, 'Slovakia');
INSERT INTO countries (id, name) VALUES (39, 'Slovenia');
INSERT INTO countries (id, name) VALUES (40, 'Spain');
INSERT INTO countries (id, name) VALUES (41, 'Sweden');
INSERT INTO countries (id, name) VALUES (42, 'Switzerland');
INSERT INTO countries (id, name) VALUES (43, 'Turkey');
INSERT INTO countries (id, name) VALUES (44, 'Ukraine');
INSERT INTO countries (id, name) VALUES (45, 'United Kingdom');
INSERT INTO countries (id, name) VALUES (46, 'Vatican City');


